### ISSUE TITLE
Releases for linux & darwin builds

### ISSUE THREAD

**Issue by stevehodgkiss** [Shopify/ejson2env#7]
Hi 👋 

Thanks for ejson & ejson2env!

Would you be able to provide the linux & darwin builds as part of Github releases, like the [EJSON v1.2.0 release](https://github.com/Shopify/ejson/releases/tag/v1.2.0))?

**Comment by noqcks** [comment]
+1 cc: @catherinejones

**Comment by catherinejones** [comment]
I will definitely take a look at doing this! :)

**Comment by catherinejones** [comment]
The latest release of ejson2env is available through Github releases, and I will upload future releases this way as well! Please let me know if you have any issues!
