### ISSUE TITLE
Success message on command completion

### ISSUE THREAD

**Issue by noqcks** [Shopify/ejson2env#8]
If ejson2env completed with exit code 0 would be nice to have a print statement declaring success.

**Comment by catherinejones** [comment]
Could I ask for the use case? Typically unix commands succeed silently, aside from their exit codes, and I don't want ejson2env to break convention.

I might suggest checking the exit code and printing a message then, if you're running ejson2env in a startup script?

```bash
ejson2env
if [ $? -eq 0 ]; then
  echo "ejson2env has run"
fi
```

**Comment by noqcks** [comment]
Agreed. Makes more sense to check exit code in external script
